version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null, unique]
  - name: dim_product
    columns:
      - name: product_key
        tests: [not_null, unique]
      - name: product_id
        tests: [not_null, unique]
  - name: dim_branch
    columns:
      - name: branch_key
        tests: [not_null, unique]
      - name: branch_id
        tests: [not_null, unique]
  - name: dim_loan_status
    columns:
      - name: loan_status_key
        tests: [not_null, unique]
  - name: fact_loan_disbursement
    columns:
      - name: loan_id
        tests: [not_null, unique]
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
